version: '3.9'

x-mysql: &mysql
  image: mysql:5.7
  container_name: master_data_tool_mysql57
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-f3WpxNreVT2NgQry}
  platform: linux/x86_64
  ports:
    - 127.0.0.1:${DB_PORT:-33306}:3306
  volumes:
    - mysql:/var/lib/mysql
  command: >
    mysqld 
      --sql-mode=NO_ENGINE_SUBSTITUTION
      --character-set-server=utf8mb4
      --innodb-file-per-table=1
      --innodb-large-prefix

services:
  mysql:
    <<: *mysql

volumes:
  mysql:
