module MasterDataTool
  class Error < StandardError
  end

  class DryRunError < StandardError
  end

  class NotLoadedError < StandardError
  end

  class VerifyFailed < StandardError
    attr_accessor errors: untyped

    def full_messages: () -> untyped
  end

  def self.config: () -> Config

  def self.configure: () { (Config) -> void } -> void

  def self.resolve_table_name: (spec_name: String, csv_path: Pathname, override_identifier: String?) -> String

  def self.need_skip_table?: (String table_name, Array[String] only, Array[String] except) -> bool
end
