#!/usr/bin/env ruby
# frozen_string_literal: true

require 'thor'
require 'master_data_tool'

environment_path = "#{Dir.pwd}/config/environment"
require environment_path

module MasterDataTool
  class CLI < Thor
    include MasterDataTool::Command::Import
    include MasterDataTool::Command::Verify
    include MasterDataTool::Command::Dump
  end
end

MasterDataTool::CLI.start(ARGV)
