#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${REPO_ROOT}"

# Load .env.test
set -a
# shellcheck source=../.env.test
source "${REPO_ROOT}/.env.test"
set +a

# Derive COMPOSE_PROJECT_NAME from current directory name
PROJECT_NAME=$(basename "${REPO_ROOT}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]/-/g')
export COMPOSE_PROJECT_NAME="${PROJECT_NAME}"

DOCKER_COMPOSE="docker compose --env-file ${REPO_ROOT}/.env.test"

echo "==> COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}"

# Step 1: Create shared bundle volume (idempotent)
if ! docker volume inspect master_data_tool_bundle >/dev/null 2>&1; then
  echo "==> Creating shared bundle volume: master_data_tool_bundle"
  docker volume create master_data_tool_bundle
else
  echo "==> Bundle volume already exists: master_data_tool_bundle"
fi

# Step 2: Start containers
echo "==> Starting containers..."
${DOCKER_COMPOSE} up -d

# Step 3: Wait for MySQL (max 30 seconds)
echo "==> Waiting for MySQL..."
MAX_WAIT=30
count=0
until ${DOCKER_COMPOSE} exec -T -e MYSQL_PWD="${DB_PASSWORD}" mysql mysql -u "${DB_USER}" -e "SELECT 1" >/dev/null 2>&1; do
  count=$((count + 1))
  if [ "${count}" -ge "${MAX_WAIT}" ]; then
    echo "Error: MySQL did not become ready within ${MAX_WAIT} seconds"
    exit 1
  fi
  echo "  waiting... (${count}/${MAX_WAIT})"
  sleep 1
done
echo "==> MySQL is ready"

# Step 4: Create database (idempotent)
echo "==> Creating database: ${DB_NAME}"
${DOCKER_COMPOSE} exec -T -e MYSQL_PWD="${DB_PASSWORD}" mysql \
  mysql -u "${DB_USER}" \
  -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`"

# Step 5: Run migrations
echo "==> Running migrations..."
${DOCKER_COMPOSE} exec -T ruby bash -c './scripts/migrate.sh'

# Step 6: Get actual host port and generate .envrc
HOST_PORT=$(${DOCKER_COMPOSE} port mysql 3306 | cut -d: -f2)
echo "==> MySQL host port: ${HOST_PORT}"

cat > "${REPO_ROOT}/.envrc" <<EOF
# auto-generated by scripts/worktree-setup.sh
# DO NOT EDIT MANUALLY
export COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
export DB_HOST=127.0.0.1
export DB_PORT=${HOST_PORT}
EOF

echo ""
echo "==> Setup complete!"
echo ""
echo "Run one of the following to activate environment variables:"
echo "  direnv allow"
echo "  source .envrc"
